pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
              multibranch:
                branchSource:
                  github:
                    repoOwner: ${owner}
                    repository: ${repoName}
                    credentialsId: ${credentialId}
            }
        }
    }
}
