// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent {
        kubernetes {
            serviceAccount "${serviceAccount}"
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: ubuntu
    command:
    - sleep
    args:
    - infinity
'''
            // Can also wrap individual steps:
            // container('shell') {
            //     sh 'hostname'
            // }
            defaultContainer 'shell'
        }
    }
    stages {
        stage('Main') {
            steps {
                sh 'hostname'
                sh "echo ${serviceAccount}"
            }
        }
    }
}
