library '_github.com_pipeline-demo-caternberg_workflowLibs' _
import de.caternberg.pipeline.helper.GlobalVars
pipeline {
    agent any
    stages {
        stage('Say Hello') {
            steps {
                echo "Hello World! ${firstname}"
                echo "${GlobalVars.foo}"
            }
        }
    }
}
