library '_github.com_pipeline-demo-caternberg_workflowLibs' _
pipeline {
    agent any
    stages {
        stage('Say Hello') {
            steps {
                echo "Hello World! ${firstname}"
            }
        }
    }
}
